export const VerificationsPlaceholder = [ 
    {
        title: "Game Seller",
        personnel_name: "Iffy Tex",
        verified_with: "PHONE_NUMBER",
        status: "success",
        createdAt: "January 15th 2025, 6:44",
    },
    {
        title: "New Frontend",
        personnel_name: "Donald Njokanma",
        verified_with: "NIN",
        status: "success",
        createdAt: "November 25th 2024, 1:45",
    },
    {
        title: "Game Seller",
        personnel_name: "Shokunbi Micheal",
        verified_with: "BVN",
        status: "success",
        createdAt: "November 6th 2024, 2:15",
    },
    {
        title: "Game Seller",
        personnel_name: "Iffy Tex",
        verified_with: "PHONE_NUMBER",
        status: "success",
        createdAt: "October 24th 2024, 12:44",
    },
    {
        title: "Lesson Teacher",
        personnel_name: "Mr Onknowo",
        verified_with: "PHONE_NUMBER",
        status: "failure",
        createdAt: "October 24th 2024, 12:43",
    },
    {
        title: "Truck driver",
        personnel_name: "John Doe",
        verified_with: "PHONE_NUMBER",
        status: "failure",
        createdAt: "October 24th 2024, 12:43",
    },
    {
        title: "Lesson Teacher",
        personnel_name: "Mr Onknowo",
        verified_with: "BVN",
        status: "failure",
        createdAt: "October 24th 2024, 12:43",
    },
]

export const RecentVett = [ 
    {
        title: "Game Seller",
        personnel_name: "Iffy Tex",
        verified_with: "PHONE_NUMBER",
        status: "success",
        createdAt: "January 15th 2025, 6:44",
    },
    {
        title: "New Frontend",
        personnel_name: "Donald Njokanma",
        verified_with: "NIN",
        status: "success",
        createdAt: "November 25th 2024, 1:45",
    },
    {
        title: "Game Seller",
        personnel_name: "Shokunbi Micheal",
        verified_with: "BVN",
        status: "success",
        createdAt: "November 6th 2024, 2:15",
    },
    {
        title: "Game Seller",
        personnel_name: "Iffy Tex",
        verified_with: "PHONE_NUMBER",
        status: "failure",
        createdAt: "October 24th 2024, 12:44",
    },
]

export const activities = {
  isLoading: false,
  isFetching: false,
  data: [
    {
      applicationName: "Test",
      applicationId: "1",
      cost: "0",
      date: "20/12/2024, 11:12 AM",
      environment: "sandbox",
      service: "bvn",
      status: "200",
    },
    {
      applicationName: "Test",
      applicationId: "1",
      cost: "0",
      date: "20/12/2024, 11:12 AM",
      environment: "live",
      service: "bvn",
      status: "200",
    },
    {
      applicationName: "Test",
      applicationId: "1",
      cost: "0",
      date: "20/12/2024, 11:12 AM",
      environment: "live",
      service: "NIN",
      status: "404",
    },
    {
      applicationName: "Sample",
      applicationId: "1",
      cost: "0",
      date: "20/12/2024, 11:12 AM",
      environment: "sandbox",
      service: "NIN",
      status: "200",
    },
  ]
}

export const application = {
    isLoading: false,
    isFetching: false,
    data: [
      {
        name: "Test",
        companyId: "1",
        id: "4508374f-77be-4956-bcdd-a83b067e8554",
        createdAt: "20/12/2024, 11:12 AM",
        public_key: "public_iYzZKh2iJuYWsWZ2_key",
        private_key: "private_TguasVOjpJ6u2Lko_key",
        status: true,
        logs: [
            {
                applicationName: "Test",
                applicationId: "1",
                id: "00001",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "live",
                service: "bvn",
                statusCode: "200",
              },
              {
                applicationName: "Test",
                applicationId: "1",
                id: "00002",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "live",
                service: "NIN",
                statusCode: "404",
              },
              {
                applicationName: "Sample",
                applicationId: "1",
                id: "00003",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "sandbox",
                service: "NIN",
                statusCode: "200",
              },
        ],
      },
      {
        name: "Sample App",
        companyId: "2",
        id: "dB08374f-77be-4956-bcdd-a83b067e8009",
        createdAt: "20/12/2024, 11:12 AM",
        public_key: "public_iYzZKh2iJuYWsWZ2_key",
        private_key: "private_TguasVOjpJ6u2Lko_key",
        status: true,
        logs: [
            {
                applicationName: "Test",
                applicationId: "1",
                id: "000001",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "live",
                service: "bvn",
                statusCode: "200",
              },
              {
                applicationName: "Test",
                applicationId: "1",
                id: "000002",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "live",
                service: "NIN",
                statusCode: "404",
              },
              {
                applicationName: "Sample",
                applicationId: "1",
                id: "000003",
                createdAt: "20/12/2024, 11:12 AM",
                environment: "sandbox",
                service: "NIN",
                statusCode: "200",
              },
        ],
      },
      {
        name: "Vettme",
        companyId: "3",
        id: "cf08374f-77be-4956-bcdd-a83b067ec419a",
        createdAt: "20/12/2024, 11:12 AM",
        public_key: "public_iYzZKh2iJuYWsWZ2_key",
        private_key: "private_TguasVOjpJ6u2Lko_key",
        status: true,
        logs: [],
      },
      {
        name: "Test App",
        companyId: "4",
        id: "j4V2374f-77be-4956-bcdd-a83b067e85ff",
        createdAt: "20/12/2024, 11:12 AM",
        public_key: "public_iYzZKh2iJuYWsWZ2_key",
        private_key: "private_TguasVOjpJ6u2Lko_key",
        status: true,
        logs: [],
      },
    ]
  }